### ISSUE TITLE
Delete Tweet Button?

### ISSUE THREAD

**Issue by Bitcross** [AndrewWYoung/TwitterClone#13]
Can someone either tell me how to add a functioning delete button for tweets or do it so I can review the code. I don't know any of the backend yet.

**Comment by deriegle** [comment]
I could code it and let you review the code. I'm not sure how to exactly explain it. I'll code it and make sure to leave good notes on what's going on.

**Comment by Bitcross** [comment]
thanks! I appreciate that.

**Comment by Bitcross** [comment]
So I'm looking at the Tweets page and was thinking that it should just be a message box with a submit button. It should then pull the user's name and profile picture dynamically. right?

**Comment by deriegle** [comment]
Yeah you're absolutely right and you shouldn't be able to create a tweet unless you're logged in. I think the create a tweet box should be on a separate page or a popup box instead. We'll have to work on that later. I made the delete button, but right now anyone can delete the tweets. I will have to change it so only the user who created the tweet can delete it later

**Comment by Bitcross** [comment]
Okay, thanks. I just needed it so I can style the page. :)

**Comment by deriegle** [comment]
In my recent pull request there, I changed it so you can only see the delete button if it's a tweet you created. Also, I changed the /tweets page so that the create-a-tweet header only shows whenever you're logged in. Thanks for styling the landing page! Those cards look & work great on the navbar

**Comment by Bitcross** [comment]
Thank you! This project is great practice for us all! Sticking with my "Stacked Deck Designs" Theme lol
